# Generated by Django 2.1.4 on 2019-10-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0008_auto_20190928_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpair',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
