# Generated by Django 2.1.4 on 2019-10-11 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0009_wordpair_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='topico.MyUser'),
        ),
    ]
